# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 49a4ef573ddf60caec220fab0c1cff2e0462d87e7c24c1d5309e1cd0bb5288d5636ad4a8caba138116ea488ee7b869cd0c41d49096f086b0ff9b6e84e8184ac0

test:
  secret_key_base: 0e86ad3c67ef49cc4bf81e004b8e338e775678b9deef1b162a36a7128e5d28d2a287b19020b8a71d175d12785b275b5373eac967c562e784a73aa5211f265c35

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
